packages:
  - .
overrides:
  "@next/env": "npm:@varlock/nextjs-integration"
allowBuilds:
  core-js: false
  msw: true
  protobufjs: false
  sharp: true
minimumReleaseAgeExclude:
  - "@posthog/core@1.29.10"
  - "@posthog/types@1.376.1"
  - posthog-js@1.376.1
  - ultracite@7.8.0
