packages:
  - .
overrides:
  "@next/env": "npm:@varlock/nextjs-integration"
allowBuilds:
  core-js: false
  msw: true
  protobufjs: false
  sharp: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.30.10'
  - '@posthog/types@1.382.0'
  - posthog-js@1.382.0
