import { type Tech, TechCategory } from "@/types/tech";

export const myStack: Tech[] = [
  {
    category: TechCategory.Frontend,
    color: "#BC52EE",
    icon: "astro",
    link: "https://astro.build/",
    name: "Astro",
  },
  {
    category: TechCategory.Runtime,
    color: "#FBf0Df",
    icon: "bun",
    link: "https://bun.com/",
    name: "Bun",
  },
  {
    category: TechCategory.CloudHosting,
    color: "#F38020",
    icon: "cloudflare",
    link: "https://cloudflare.com/",
    name: "Cloudflare",
  },
  {
    category: TechCategory.Language,
    color: "#C026D3",
    hide: true,
    icon: "csharp",
    link: "https://dotnet.microsoft.com/",
    name: "C#",
  },
  {
    category: TechCategory.Language,
    color: "#0175C2",
    hide: true,
    icon: "dart",
    link: "https://dart.dev/",
    name: "Dart",
  },
  {
    category: TechCategory.CloudHosting,
    color: "#0080FF",
    icon: "digital-ocean",
    link: "https://digitalocean.com/",
    name: "DigitalOcean",
  },
  {
    category: TechCategory.DevOps,
    color: "#2496ED",
    icon: "docker",
    link: "https://docker.com/",
    name: "Docker",
  },
  {
    category: TechCategory.Backend,
    color: "#512BD4",
    hide: true,
    icon: "dotnet",
    link: "https://dotnet.microsoft.com/",
    name: ".NET",
  },
  {
    category: TechCategory.CrossPlatform,
    color: "#47848F",
    icon: "electron",
    link: "https://electronjs.org/",
    name: "Electron",
  },
  {
    category: TechCategory.BackendServices,
    color: "#DD2C00",
    icon: "firebase",
    link: "https://firebase.google.com/",
    name: "Firebase",
  },
  {
    category: TechCategory.CrossPlatform,
    color: "#02569B",
    hide: true,
    icon: "flutter",
    link: "https://flutter.dev/",
    name: "Flutter",
  },
  {
    category: TechCategory.DevOps,
    color: "#F05032",
    icon: "git",
    link: "https://git-scm.com/",
    name: "Git",
  },
  {
    category: TechCategory.DevOps,
    color: "#181717",
    icon: "github",
    link: "https://github.com/",
    name: "GitHub",
  },
  {
    category: TechCategory.Infrastructure,
    color: "#C72E49",
    icon: "minio",
    link: "https://min.io/",
    name: "MinIO",
  },
  {
    category: TechCategory.Database,
    color: "#47A248",
    icon: "mongodb",
    link: "https://mongodb.com/",
    name: "MongoDB",
  },
  {
    category: TechCategory.Database,
    color: "#4479A1",
    icon: "mysql",
    link: "https://mysql.com/",
    name: "MySQL",
  },
  {
    category: TechCategory.Database,
    color: "#4169E1",
    icon: "postgresql",
    link: "https://postgresql.org/",
    name: "PostgreSQL",
  },
  {
    category: TechCategory.Language,
    color: "#3776AB",
    hide: true,
    icon: "python",
    link: "https://python.org/",
    name: "Python",
  },
  {
    category: TechCategory.Infrastructure,
    color: "#FF6600",
    icon: "rabbitmq",
    link: "https://rabbitmq.com/",
    name: "RabbitMQ",
  },
  {
    category: TechCategory.Frontend,
    color: "#61DAFB",
    icon: "react",
    link: "https://reactjs.org/",
    name: "React",
  },
  {
    category: TechCategory.CrossPlatform,
    color: "#61DAFB",
    icon: "react",
    link: "https://reactnative.dev/",
    name: "React Native",
  },
  {
    category: TechCategory.BuildTools,
    color: "#FF7E17",
    icon: "rolldown",
    link: "https://rolldown.rs/",
    name: "Rolldown",
  },
  {
    category: TechCategory.Language,
    color: "#000000",
    icon: "rust",
    link: "https://rust-lang.org",
    name: "Rust",
  },
  {
    category: TechCategory.Styling,
    color: "#000000",
    icon: "shadcn",
    link: "https://ui.shadcn.com/",
    name: "shadcn-ui",
  },
  {
    category: TechCategory.BackendServices,
    color: "#4945FF",
    icon: "strapi",
    link: "https://strapi.io/",
    name: "Strapi",
  },
  {
    category: TechCategory.Styling,
    color: "#06B6D4",
    icon: "tailwind",
    link: "https://tailwindcss.com/",
    name: "Tailwind CSS",
  },
  {
    category: TechCategory.BuildTools,
    color: "#EF4444",
    icon: "turborepo",
    link: "https://turborepo.com/",
    name: "Turborepo",
  },
  {
    category: TechCategory.Language,
    color: "#3178C6",
    icon: "typescript",
    link: "https://typescriptlang.org/",
    name: "TypeScript",
  },
  {
    category: TechCategory.CloudHosting,
    color: "#000000",
    icon: "vercel",
    link: "https://vercel.com/",
    name: "Vercel",
  },
  {
    category: TechCategory.Database,
    color: "#FF4438",
    icon: "redis",
    link: "https://redis.io/",
    name: "Redis",
  },
  {
    category: TechCategory.Runtime,
    color: "#5FA04E",
    icon: "node",
    link: "https://nodejs.org/",
    name: "Node.js",
  },
  {
    category: TechCategory.Observability,
    color: "#F46800",
    icon: "grafana",
    link: "https://grafana.com/",
    name: "Grafana",
  },
  {
    category: TechCategory.Observability,
    color: "#E6522C",
    icon: "prometheus",
    link: "https://prometheus.io/",
    name: "Prometheus",
  },
  {
    category: TechCategory.Frontend,
    color: "#000000",
    icon: "nextjs",
    link: "https://nextjs.org/",
    name: "Next.js",
  },
  {
    category: TechCategory.BuildTools,
    color: "#646CFF",
    icon: "vite",
    link: "https://vitejs.dev/",
    name: "Vite",
  },
] as const;

export function getTechByName(name: string) {
  return myStack.find((tech) => tech.name === name);
}

export function getTechsByName(names: string[]) {
  const techs = names.map((name) => getTechByName(name));
  return techs.filter((tech) => tech !== undefined) as Tech[];
}
