import {
  AstroIcon,
  BunIcon,
  CloudflareIcon,
  DartIcon,
  DigitalOceanIcon,
  DockerIcon,
  DotnetIcon,
  ElectronIcon,
  FirebaseIcon,
  FlutterIcon,
  GitIcon,
  MinIOIcon,
  MongoDBIcon,
  MySQLIcon,
  PostgreSQLIcon,
  PythonIcon,
  RabbitMQIcon,
  ReactIcon,
  ShadcnIcon,
  StrapiIcon,
  TailwindIcon,
  TurborepoIcon,
  TypeScriptIcon,
  RedisIcon,
  NodeIcon,
  GrafanaIcon,
  ViteIcon,
  PrometheusIcon,
  GitHubIcon,
  VercelIcon,
  NextJSIcon,
  CsharpIcon,
  RolldownIcon,
} from "@/components/svg-icons";
import { Tech, TechCategory } from "../types/tech";

export const myStack: Tech[] = [
  {
    name: "Astro",
    link: "https://astro.build/",
    color: "#BC52EE",
    category: TechCategory.Frontend,
    icon: <AstroIcon />,
  },
  {
    name: "Bun",
    link: "https://bun.com/",
    color: "#FBf0Df",
    category: TechCategory.Backend,
    icon: <BunIcon />,
  },
  {
    name: "Cloudflare",
    link: "https://cloudflare.com/",
    color: "#F38020",
    category: TechCategory.Cloud,
    icon: <CloudflareIcon />,
  },
  {
    name: "C#",
    link: "https://dotnet.microsoft.com/",
    color: "#C026D3",
    category: TechCategory.Language,
    icon: <CsharpIcon />,
  },
  {
    name: "Dart",
    link: "https://dart.dev/",
    color: "#0175C2",
    category: TechCategory.Language,
    icon: <DartIcon />,
  },
  {
    name: "DigitalOcean",
    link: "https://digitalocean.com/",
    color: "#0080FF",
    category: TechCategory.Cloud,
    icon: <DigitalOceanIcon />,
  },
  {
    name: "Docker",
    link: "https://docker.com/",
    color: "#2496ED",
    category: TechCategory.DevOps,
    icon: <DockerIcon />,
  },
  {
    name: ".NET",
    link: "https://dotnet.microsoft.com/",
    color: "#512BD4",
    category: TechCategory.Backend,
    icon: <DotnetIcon />,
  },
  {
    name: "Electron",
    link: "https://electronjs.org/",
    color: "#47848F",
    category: TechCategory.MobileDesktop,
    icon: <ElectronIcon />,
  },
  {
    name: "Firebase",
    link: "https://firebase.google.com/",
    color: "#DD2C00",
    category: TechCategory.Cloud,
    icon: <FirebaseIcon />,
  },
  {
    name: "Flutter",
    link: "https://flutter.dev/",
    color: "#02569B",
    category: TechCategory.MobileDesktop,
    icon: <FlutterIcon />,
  },
  {
    name: "Git",
    link: "https://git-scm.com/",
    color: "#F05032",
    category: TechCategory.DevOps,
    icon: <GitIcon />,
  },
  {
    name: "GitHub",
    link: "https://github.com/",
    color: "#181717",
    category: TechCategory.DevOps,
    icon: <GitHubIcon />,
  },
  {
    name: "MinIO",
    link: "https://min.io/",
    color: "#C72E49",
    category: TechCategory.Infrastructure,
    icon: <MinIOIcon />,
  },
  {
    name: "MongoDB",
    link: "https://mongodb.com/",
    color: "#47A248",
    category: TechCategory.Database,
    icon: <MongoDBIcon />,
  },
  {
    name: "MySQL",
    link: "https://mysql.com/",
    color: "#4479A1",
    category: TechCategory.Database,
    icon: <MySQLIcon />,
  },
  {
    name: "PostgreSQL",
    link: "https://postgresql.org/",
    color: "#4169E1",
    category: TechCategory.Database,
    icon: <PostgreSQLIcon />,
  },
  {
    name: "Python",
    link: "https://python.org/",
    color: "#3776AB",
    category: TechCategory.Language,
    icon: <PythonIcon />,
  },
  {
    name: "RabbitMQ",
    link: "https://rabbitmq.com/",
    color: "#FF6600",
    category: TechCategory.Infrastructure,
    icon: <RabbitMQIcon />,
  },
  {
    name: "React",
    link: "https://reactjs.org/",
    color: "#61DAFB",
    category: TechCategory.Frontend,
    icon: <ReactIcon />,
  },
  {
    name: "React Native",
    link: "https://reactnative.dev/",
    color: "#61DAFB",
    category: TechCategory.MobileDesktop,
    icon: <ReactIcon />,
  },
  {
    name: "Rolldown",
    link: "https://rolldown.rs/",
    color: "#FF7E17",
    category: TechCategory.DevOps,
    icon: <RolldownIcon />,
  },
  {
    name: "shadcn-ui",
    link: "https://ui.shadcn.com/",
    color: "#000000",
    category: TechCategory.UILibrary,
    icon: <ShadcnIcon />,
  },
  {
    name: "Strapi",
    link: "https://strapi.io/",
    color: "#4945FF",
    category: TechCategory.CMS,
    icon: <StrapiIcon />,
  },
  {
    name: "Tailwind CSS",
    link: "https://tailwindcss.com/",
    color: "#06B6D4",
    category: TechCategory.UILibrary,
    icon: <TailwindIcon />,
  },
  {
    name: "Turborepo",
    link: "https://turborepo.com/",
    color: "#EF4444",
    category: TechCategory.DevOps,
    icon: <TurborepoIcon />,
  },
  {
    name: "TypeScript",
    link: "https://typescriptlang.org/",
    color: "#3178C6",
    category: TechCategory.Language,
    icon: <TypeScriptIcon />,
  },
  {
    name: "Vercel",
    link: "https://vercel.com/",
    color: "#000000",
    category: TechCategory.Cloud,
    icon: <VercelIcon />,
  },
  {
    name: "Redis",
    link: "https://redis.io/",
    color: "#FF4438",
    category: TechCategory.Database,
    icon: <RedisIcon />,
  },
  {
    name: "Node.js",
    link: "https://nodejs.org/",
    color: "#5FA04E",
    category: TechCategory.Backend,
    icon: <NodeIcon />,
  },
  {
    name: "Grafana",
    link: "https://grafana.com/",
    color: "#F46800",
    category: TechCategory.Infrastructure,
    icon: <GrafanaIcon />,
  },
  {
    name: "Prometheus",
    link: "https://prometheus.io/",
    color: "#E6522C",
    category: TechCategory.Infrastructure,
    icon: <PrometheusIcon />,
  },
  {
    name: "Next.js",
    link: "https://nextjs.org/",
    color: "#000000",
    category: TechCategory.Frontend,
    icon: <NextJSIcon />,
  },
  {
    name: "Vite",
    link: "https://vitejs.dev/",
    color: "#646CFF",
    category: TechCategory.Frontend,
    icon: <ViteIcon />,
  },
] as const;

export function getTechByName(name: string) {
  return myStack.find((tech) => tech.name === name);
}

export function getTechsByName(names: string[]) {
  const techs = names.map((name) => getTechByName(name));
  return techs.filter((tech) => tech !== undefined) as Tech[];
}
