import { type Tech, TechCategory } from "@/types/tech";

export const myStack: Tech[] = [
  {
    name: "Astro",
    link: "https://astro.build/",
    color: "#BC52EE",
    category: TechCategory.Frontend,
    icon: "astro",
  },
  {
    name: "Bun",
    link: "https://bun.com/",
    color: "#FBf0Df",
    category: TechCategory.Runtime,
    icon: "bun",
  },
  {
    name: "Cloudflare",
    link: "https://cloudflare.com/",
    color: "#F38020",
    category: TechCategory.CloudHosting,
    icon: "cloudflare",
  },
  {
    name: "C#",
    link: "https://dotnet.microsoft.com/",
    color: "#C026D3",
    category: TechCategory.Language,
    icon: "csharp",
    hide: true,
  },
  {
    name: "Dart",
    link: "https://dart.dev/",
    color: "#0175C2",
    category: TechCategory.Language,
    icon: "dart",
    hide: true,
  },
  {
    name: "DigitalOcean",
    link: "https://digitalocean.com/",
    color: "#0080FF",
    category: TechCategory.CloudHosting,
    icon: "digital-ocean",
  },
  {
    name: "Docker",
    link: "https://docker.com/",
    color: "#2496ED",
    category: TechCategory.DevOps,
    icon: "docker",
  },
  {
    name: ".NET",
    link: "https://dotnet.microsoft.com/",
    color: "#512BD4",
    category: TechCategory.Backend,
    icon: "dotnet",
    hide: true,
  },
  {
    name: "Electron",
    link: "https://electronjs.org/",
    color: "#47848F",
    category: TechCategory.CrossPlatform,
    icon: "electron",
  },
  {
    name: "Firebase",
    link: "https://firebase.google.com/",
    color: "#DD2C00",
    category: TechCategory.BackendServices,
    icon: "firebase",
  },
  {
    name: "Flutter",
    link: "https://flutter.dev/",
    color: "#02569B",
    category: TechCategory.CrossPlatform,
    icon: "flutter",
    hide: true,
  },
  {
    name: "Git",
    link: "https://git-scm.com/",
    color: "#F05032",
    category: TechCategory.DevOps,
    icon: "git",
  },
  {
    name: "GitHub",
    link: "https://github.com/",
    color: "#181717",
    category: TechCategory.DevOps,
    icon: "github",
  },
  {
    name: "MinIO",
    link: "https://min.io/",
    color: "#C72E49",
    category: TechCategory.Infrastructure,
    icon: "minio",
  },
  {
    name: "MongoDB",
    link: "https://mongodb.com/",
    color: "#47A248",
    category: TechCategory.Database,
    icon: "mongodb",
  },
  {
    name: "MySQL",
    link: "https://mysql.com/",
    color: "#4479A1",
    category: TechCategory.Database,
    icon: "mysql",
  },
  {
    name: "PostgreSQL",
    link: "https://postgresql.org/",
    color: "#4169E1",
    category: TechCategory.Database,
    icon: "postgresql",
  },
  {
    name: "Python",
    link: "https://python.org/",
    color: "#3776AB",
    category: TechCategory.Language,
    icon: "python",
    hide: true,
  },
  {
    name: "RabbitMQ",
    link: "https://rabbitmq.com/",
    color: "#FF6600",
    category: TechCategory.Infrastructure,
    icon: "rabbitmq",
  },
  {
    name: "React",
    link: "https://reactjs.org/",
    color: "#61DAFB",
    category: TechCategory.Frontend,
    icon: "react",
  },
  {
    name: "React Native",
    link: "https://reactnative.dev/",
    color: "#61DAFB",
    category: TechCategory.CrossPlatform,
    icon: "react",
  },
  {
    name: "Rolldown",
    link: "https://rolldown.rs/",
    color: "#FF7E17",
    category: TechCategory.BuildTools,
    icon: "rolldown",
  },
  {
    name: "Rust",
    link: "https://rust-lang.org",
    color: "#000000",
    category: TechCategory.Language,
    icon: "rust",
  },
  {
    name: "shadcn-ui",
    link: "https://ui.shadcn.com/",
    color: "#000000",
    category: TechCategory.Styling,
    icon: "shadcn",
  },
  {
    name: "Strapi",
    link: "https://strapi.io/",
    color: "#4945FF",
    category: TechCategory.BackendServices,
    icon: "strapi",
  },
  {
    name: "Tailwind CSS",
    link: "https://tailwindcss.com/",
    color: "#06B6D4",
    category: TechCategory.Styling,
    icon: "tailwind",
  },
  {
    name: "Turborepo",
    link: "https://turborepo.com/",
    color: "#EF4444",
    category: TechCategory.BuildTools,
    icon: "turborepo",
  },
  {
    name: "TypeScript",
    link: "https://typescriptlang.org/",
    color: "#3178C6",
    category: TechCategory.Language,
    icon: "typescript",
  },
  {
    name: "Vercel",
    link: "https://vercel.com/",
    color: "#000000",
    category: TechCategory.CloudHosting,
    icon: "vercel",
  },
  {
    name: "Redis",
    link: "https://redis.io/",
    color: "#FF4438",
    category: TechCategory.Database,
    icon: "redis",
  },
  {
    name: "Node.js",
    link: "https://nodejs.org/",
    color: "#5FA04E",
    category: TechCategory.Runtime,
    icon: "node",
  },
  {
    name: "Grafana",
    link: "https://grafana.com/",
    color: "#F46800",
    category: TechCategory.Observability,
    icon: "grafana",
  },
  {
    name: "Prometheus",
    link: "https://prometheus.io/",
    color: "#E6522C",
    category: TechCategory.Observability,
    icon: "prometheus",
  },
  {
    name: "Next.js",
    link: "https://nextjs.org/",
    color: "#000000",
    category: TechCategory.Frontend,
    icon: "nextjs",
  },
  {
    name: "Vite",
    link: "https://vitejs.dev/",
    color: "#646CFF",
    category: TechCategory.BuildTools,
    icon: "vite",
  },
] as const;

export function getTechByName(name: string) {
  return myStack.find((tech) => tech.name === name);
}

export function getTechsByName(names: string[]) {
  const techs = names.map((name) => getTechByName(name));
  return techs.filter((tech) => tech !== undefined) as Tech[];
}
